trigger:
  - main  # or your desired branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'backend-dummy'
  branchName: $(Build.SourceBranchName)

steps:
- checkout: self

- script: |
    echo "Sanitizing branch name..."
    cleanBranch=$(echo $(branchName) | sed 's/\//-/g')
    echo "##vso[task.setvariable variable=cleanBranchName]$cleanBranch"
    echo "##vso[task.setvariable variable=imageTag]$cleanBranch-$(Build.BuildId)-$(Date:yyyyMMdd)$(Rev:.r)"
  displayName: Generate tag

- task: Docker@2
  displayName: Build Docker image
  inputs:
    containerRegistry: 'dw-acr-connection'  # 👈 Replace with your actual ACR service connection name
    command: build
    repository: $(imageName)
    Dockerfile: '**/Dockerfile'
    tags: |
      $(imageTag)

- task: Docker@2
  displayName: Push Docker image to ACR
  inputs:
    containerRegistry: 'dw-acr-connection'
    command: push
    repository: $(imageName)
    tags: |
      $(imageTag)
