trigger:
  - main  # or your branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'backend-dummy'
  buildDate: $[format('{0:yyyyMMdd-HHmmss}', pipeline.startTime)]
  branchName: $[replace(variables['Build.SourceBranchName'], '/', '-')]
  imageTag: '$(branchName)-$(Build.BuildId)-$(buildDate)'

steps:
- checkout: self

- task: Docker@2
  displayName: Build Docker image
  inputs:
    containerRegistry: 'dw-acr-connection'
    command: build
    repository: $(imageName)
    Dockerfile: '**/Dockerfile'
    tags: |
      $(imageTag)

- task: Docker@2
  displayName: Push Docker image to ACR
  inputs:
    containerRegistry: 'dw-acr-connection'
    command: push
    repository: $(imageName)
    tags: |
      $(imageTag)
